default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: blog
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default


#
production:
  <<: *default
  username: blog
  password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>
